// DHAMAKA's signature AI mechanic — Price Radar.
//
// Every product carries a small simulated ~60-day price-history dataset
// (src/lib/dhamaka/catalog.ts). analyzePriceTrend() reads that data — real
// arithmetic on the numbers, not a lookup of how the fixture was generated —
// and decides which of four honest states the listing is in: sitting at its
// floor, still sliding down, creeping back up, or holding steady. That state
// drives both the label and a one-line justification sentence.
//
// A note on the justification sentence: the brief suggested optionally
// reusing src/app/api/style-ai/route.ts's streaming-call pattern for a
// live-generated line. That route's system prompt is hardcoded to always
// answer with three formatted outfit picks from a catalog — it isn't a
// general-purpose one-liner endpoint, and editing it is out of scope here.
// Calling it as-is for this would either get ignored (producing an
// unrelated 3-item outfit list where a single price sentence belongs) or
// require rewriting shared, already-shipped behavior other themes depend on.
// So the justification is generated by a small deterministic writer here
// instead: several hand-written variants per trend state, chosen per
// product via a stable hash of its id (not Math.random — same product
// always reads the same sentence, no hydration mismatch). This is the
// "static fallback sentence" the brief asked for, used as the primary path
// rather than a rare failure case, and it's honest about being static
// rather than quietly pretending to be a live model call.

import type { PricePoint } from '@/lib/dhamaka/catalog'

export type PriceRadarTone = 'floor' | 'wait' | 'urgent' | 'steady'

export interface PriceRadarResult {
  tone: PriceRadarTone
  label: string
  justification: string
}

function hashString(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = (h * 31 + s.charCodeAt(i)) >>> 0
  }
  return h
}

function pick<T>(arr: T[], seed: string): T {
  return arr[hashString(seed) % arr.length]
}

const JUSTIFICATIONS: Record<PriceRadarTone, string[]> = {
  floor: [
    'This is the lowest this listing has been all season — the discount won\'t go deeper from here.',
    'Price history shows this is rock bottom for this piece right now — stock at this price rarely lasts.',
    'Sixty days of tracking and this is the cheapest this has ever shown up. This is the moment to grab it.',
    'The price has already done its dropping — this is the floor, not a stop on the way down.',
  ],
  wait: [
    'The price is still easing down — holding off a few more days should land you a slightly better number.',
    'This one hasn\'t bottomed out yet. The trend says patience gets you a cheaper tag, not a missed deal.',
    'Prices like this usually keep sliding a little longer before they flatten out — no rush to buy today.',
    'The tracker shows this still trending down — worth a second look in a few days before you commit.',
  ],
  urgent: [
    'This has been climbing back up for weeks — today\'s price is the best you\'ll see for a while.',
    'The trend is heading the wrong way for buyers. Lock this in now before the next bump.',
    'Prices on this one have been creeping up steadily — waiting typically costs more, not less.',
    'This is on its way back to full price. Today\'s number won\'t stick around long.',
  ],
  steady: [
    'This price has barely moved in two months — it\'s a fair, dependable deal rather than a fleeting one.',
    'No real swings either way here — a solid price you can act on whenever suits you.',
    'This one\'s been flat for weeks. Today\'s tag is simply the going rate, no urgency games attached.',
    'Steady as it goes — this price isn\'t chasing a trend up or down, so there\'s no clock to beat.',
  ],
}

// Reads the raw history + current price and returns the honest state —
// never trusts a stored "this is the deal" flag, always recomputes.
export function analyzePriceTrend(history: PricePoint[] | null, currentPrice: number, seedKey: string): PriceRadarResult {
  if (!history || history.length < 4) {
    return { tone: 'steady', label: 'Tracking this price', justification: pick(JUSTIFICATIONS.steady, seedKey) }
  }

  const prices = history.map(h => h.price)
  const minPrice = Math.min(...prices, currentPrice)
  const recentWindow = Math.max(3, Math.floor(prices.length / 3))
  const last = prices.slice(-recentWindow)
  const prev = prices.slice(-recentWindow * 2, -recentWindow)
  const avgLast = last.reduce((a, b) => a + b, 0) / last.length
  const avgPrev = prev.length ? prev.reduce((a, b) => a + b, 0) / prev.length : avgLast
  const delta = avgLast - avgPrev
  const deltaPct = avgPrev > 0 ? delta / avgPrev : 0
  const atFloor = currentPrice <= minPrice + Math.max(5, minPrice * 0.01)

  if (atFloor) {
    return { tone: 'floor', label: 'Lowest price in 60 days', justification: pick(JUSTIFICATIONS.floor, seedKey) }
  }

  if (deltaPct < -0.02) {
    const days = deltaPct < -0.06 ? 2 : deltaPct < -0.035 ? 3 : 5
    return { tone: 'wait', label: `Price dropping — buy in ${days} days for less`, justification: pick(JUSTIFICATIONS.wait, seedKey) }
  }

  if (deltaPct > 0.02) {
    return { tone: 'urgent', label: 'Buy now, this won\'t get cheaper this season', justification: pick(JUSTIFICATIONS.urgent, seedKey) }
  }

  return { tone: 'steady', label: 'Stable price — fair deal, no rush', justification: pick(JUSTIFICATIONS.steady, seedKey) }
}

const TONE_STYLE: Record<PriceRadarTone, { bg: string; fg: string }> = {
  floor: { bg: 'var(--dh-yellow)', fg: 'var(--dh-yellow-ink)' },
  wait: { bg: 'var(--dh-ink)', fg: 'var(--dh-bg)' },
  urgent: { bg: 'var(--dh-red)', fg: 'var(--dh-red-ink)' },
  steady: { bg: 'rgba(255,255,255,0.14)', fg: 'var(--dh-ink)' },
}

const TONE_ICON: Record<PriceRadarTone, string> = {
  floor: '⚡',
  wait: '⏳',
  urgent: '📈',
  steady: '📡',
}

// Compact badge — product cards.
export function DhamakaPriceRadarBadge({ history, currentPrice, seedKey }: { history: PricePoint[] | null; currentPrice: number; seedKey: string }) {
  const result = analyzePriceTrend(history, currentPrice, seedKey)
  const style = TONE_STYLE[result.tone]
  return (
    <span
      className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wide px-2 py-1 rounded"
      style={{ background: style.bg, color: style.fg }}
    >
      <span aria-hidden>{TONE_ICON[result.tone]}</span>
      {result.label}
    </span>
  )
}

// Full panel — PDP. Shows the label plus the one-line justification.
export function DhamakaPriceRadarPanel({ history, currentPrice, seedKey }: { history: PricePoint[] | null; currentPrice: number; seedKey: string }) {
  const result = analyzePriceTrend(history, currentPrice, seedKey)
  const style = TONE_STYLE[result.tone]
  return (
    <div className="rounded-lg border p-4" style={{ borderColor: 'var(--dh-line)', background: 'var(--dh-card)' }}>
      <div className="flex items-center gap-2 mb-2">
        <span
          className="inline-flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wide px-2.5 py-1 rounded"
          style={{ background: style.bg, color: style.fg }}
        >
          <span aria-hidden>{TONE_ICON[result.tone]}</span>
          Price Radar
        </span>
      </div>
      <p className="text-sm font-semibold mb-1" style={{ color: 'var(--dh-ink)' }}>{result.label}</p>
      <p className="text-xs leading-relaxed" style={{ color: 'var(--dh-ink-muted)' }}>{result.justification}</p>
    </div>
  )
}
