-- WearOn Platform — AI Try-On & Model Shot

-- 1. AI credits per seller (separate from try-ons)
alter table profiles add column if not exists ai_credits int not null default 0;

-- Monthly credit grants per plan (used by cron/webhook to top up)
-- free: 0, starter: 20, growth: 75, pro: 200, enterprise: 500

-- 2. AI model shots generated by sellers for products
create table if not exists ai_model_shots (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid references profiles(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade,
  garment_image_url text not null,
  preset_model_key text,          -- e.g. "fair_standing", "medium_walking"
  result_image_url text,
  result_video_url text,
  higgsfield_request_id text,     -- for polling video status
  fal_request_id text,            -- for polling image status
  status text default 'pending' check (status in ('pending', 'generating_image', 'generating_video', 'completed', 'failed')),
  output_type text default 'image' check (output_type in ('image', 'video', 'both')),
  credits_used int default 0,
  error_message text,
  created_at timestamptz default now(),
  completed_at timestamptz
);
create index if not exists ai_shots_seller_idx on ai_model_shots(seller_id, created_at desc);
create index if not exists ai_shots_product_idx on ai_model_shots(product_id);

-- 3. Buyer try-on jobs (triggered from store product pages)
create table if not exists buyer_tryons (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid references profiles(id) on delete cascade not null,
  product_id uuid references products(id) on delete cascade,
  garment_image_url text not null,
  buyer_image_temp_url text,      -- temporary, deleted after generation
  result_image_url text,
  result_video_url text,
  higgsfield_request_id text,
  fal_request_id text,
  status text default 'pending' check (status in ('pending', 'generating_image', 'generating_video', 'completed', 'failed')),
  output_type text default 'both' check (output_type in ('image', 'video', 'both')),
  credits_used int default 0,
  error_message text,
  created_at timestamptz default now(),
  completed_at timestamptz
);
create index if not exists buyer_tryons_seller_idx on buyer_tryons(seller_id, created_at desc);

-- 4. AI credit transactions (audit trail)
create table if not exists ai_credit_transactions (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid references profiles(id) on delete cascade not null,
  amount int not null,                             -- positive = credit, negative = debit
  reason text not null,                            -- 'monthly_grant', 'model_shot', 'buyer_tryon', 'topup'
  reference_id uuid,                               -- ai_model_shots.id or buyer_tryons.id
  balance_after int not null,
  created_at timestamptz default now()
);
create index if not exists ai_txn_seller_idx on ai_credit_transactions(seller_id, created_at desc);

-- 5. RLS
alter table ai_model_shots enable row level security;
alter table buyer_tryons enable row level security;
alter table ai_credit_transactions enable row level security;

create policy "service role all ai_model_shots" on ai_model_shots for all to service_role using (true) with check (true);
create policy "service role all buyer_tryons" on buyer_tryons for all to service_role using (true) with check (true);
create policy "service role all ai_credit_transactions" on ai_credit_transactions for all to service_role using (true) with check (true);

create policy "seller owns ai_model_shots" on ai_model_shots for all to authenticated using (seller_id = auth.uid()) with check (seller_id = auth.uid());
create policy "seller owns buyer_tryons" on buyer_tryons for all to authenticated using (seller_id = auth.uid()) with check (seller_id = auth.uid());
create policy "seller owns ai_credit_transactions" on ai_credit_transactions for select to authenticated using (seller_id = auth.uid());

-- 6. RPC: deduct AI credits atomically
create or replace function deduct_ai_credits(
  p_seller_id uuid,
  p_amount int,
  p_reason text,
  p_reference_id uuid default null
)
returns int  -- returns new balance, or -1 if insufficient
language plpgsql security definer as $$
declare
  v_current int;
  v_new int;
begin
  select ai_credits into v_current from profiles where id = p_seller_id for update;
  if v_current < p_amount then return -1; end if;
  v_new := v_current - p_amount;
  update profiles set ai_credits = v_new where id = p_seller_id;
  insert into ai_credit_transactions(seller_id, amount, reason, reference_id, balance_after)
    values (p_seller_id, -p_amount, p_reason, p_reference_id, v_new);
  return v_new;
end;
$$;

-- 7. RPC: grant AI credits
create or replace function grant_ai_credits(
  p_seller_id uuid,
  p_amount int,
  p_reason text
)
returns int
language plpgsql security definer as $$
declare
  v_new int;
begin
  update profiles set ai_credits = ai_credits + p_amount where id = p_seller_id returning ai_credits into v_new;
  insert into ai_credit_transactions(seller_id, amount, reason, balance_after)
    values (p_seller_id, p_amount, p_reason, v_new);
  return v_new;
end;
$$;
